-- employees (scott 의 emp 통일개념) 
-- first_name, last_name, job_id 조회   
SELECT e.LAST_NAME, e.FIRST_NAME, e.JOB_ID 
FROM EMPLOYEES e;

-- job_id 중복제외 후 조회
SELECT DISTINCT e.JOB_ID
FROM EMPLOYEES e;

-- 사번이 176인 사원의 last_name과 부서 번호 조회
SELECT e.LAST_NAME, e.DEPARTMENT_ID
FROM EMPLOYEES e
WHERE e.EMPLOYEE_ID = 176;

SELECT  e.LAST_NAME, e.SALARY
FROM EMPLOYEES e
WHERE e.SALARY >= 12000;

SELECT e.LAST_NAME, e.SALARY
FROM EMPLOYEES e
WHERE NOT (e.SALARY >= 5000 AND e.SALARY <= 12000);



SELECT e.LAST_NAME, e.SALARY
FROM EMPLOYEES e
WHERE e.SALARY < 5000 OR e.SALARY > 12000;


-- IN
-- 20,50 번 부서에 근무하는 사원 조회(LAST_NAME,부서번호), LAST_NAME 오름차순
SELECT e.LAST_NAME, e.DEPARTMENT_ID
FROM EMPLOYEES e
WHERE e.DEPARTMENT_ID IN (20,50) ORDER BY e.LAST_NAME ASC;

-- ㄴSALARY 2500,3500,7000, 이 아니며 , 묵무가 SA_REP, STCLERK 가 아닌 사원 조회
SELECT *
FROM EMPLOYEES e 
WHERE E.SALARY NOT IN (2500,3500,7000) AND E.JOB_ID NOT IN ('SA_REP, STCLERK');

-- 날짜 데이터 '' 사용
-- 고용일이 2015년 사원 조회(2014-01-01 ~ 2014-12-31)
SELECT *
FROM EMPLOYEES e 
WHERE E.HIRE_DATE >= '2014-01-01' AND E.HIRE_DATE <= '2014-12-31';

SELECT *
FROM EMPLOYEES e 
WHERE E.HIRE_DATE BETWEEN '2014-01-01' AND  '2014-12-31';

-- LIKE
-- LAST_NAME 에 u 가 포함되는 사원들의 사번, LAST_NAME 조회
SELECT E.EMPLOYEE_ID, E.LAST_NAME
FROM EMPLOYEES e 
WHERE e.LAST_name LIKE '%U%';
-- LAST_NAME 의 4번째 글자가 a인 사원들의 사번 LAST_NAME 조회
SELECT E.EMPLOYEE_ID, E.LAST_NAME
FROM EMPLOYEES e 
WHERE e.LAST_name LIKE '___a%';
-- LAST_NAME 에 a 혹은 글자가 있는 사원들의 사번, LAST_NAME 조회(LAST_NAME 내림차순) 
SELECT E.EMPLOYEE_ID, E.LAST_NAME
FROM EMPLOYEES e 
WHERE e.LAST_name LIKE '%a%' OR e.LAST_NAME LIKE '%e%' ORDER BY e.LAST_NAME  DESC;
-- LAST_NAME 에 a와 e 글자가 있는 사원들의 사번, LAST_NAME 조회(LAST_NAME 내림차순)
SELECT E.EMPLOYEE_ID, E.LAST_NAME
FROM EMPLOYEES e 
WHERE e.LAST_name LIKE '%a%e%' OR e.LAST_NAME LIKE '%e%a%' ORDER BY e.LAST_NAME  DESC;

-- IS NULL
-- 매니저가 없는 사원들의 LAST_NAME, JOB_ID 조회
SELECT E.LAST_NAME, E.JOB_ID
FROM EMPLOYEES e
WHERE E.MANAGER_ID IS NULL

-- WT_CLERK인 직업을 가진 사원이 없는 부서 번호 조회(단, 부서번호가 널 값인 부서 제외)
SELECT DISTINCT E.DEPARTMENT_ID
FROM EMPLOYEES e
WHERE E.JOB_ID != 'ST_CLERK' AND E.DEPARTMENT_ID IS NOT NULL;

-- COMMISSION_PCT가 NULL 이 아닌 사원들 중에서 COMMISSIOM=SALARY * COMMISSION_PCT 를 구한다
-- 계산 결과와 함께 사번, FIRST_NAME,JOB_ID 출력
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.JOB_ID, E.SALARY * E.COMMISSION_PCT AS COMMISSION
FROM EMPLOYEES e
WHERE E.COMMISSION_PCT IS NOT NULL;
L











