INSERT INTO GENRE(GENRE_NAME)
VALUES('Fiction');
INSERT INTO GENRE(GENRE_NAME)
VALUES('Non-fiction');
INSERT INTO GENRE(GENRE_NAME)
VALUES('Fantasy');
INSERT INTO GENRE(GENRE_NAME)
VALUES('Dystopian');
INSERT INTO GENRE(GENRE_NAME)
VALUES('Romance');
INSERT INTO GENRE(GENRE_NAME)
VALUES('Programming');
INSERT INTO GENRE(GENRE_NAME)
VALUES('Philosophy');

--
INSERT INTO NOVEL(TITLE,AUTHOR,GENRE_ID,PUBLISHED_DATE,AVAILABLE)
values('The Great Gatsby','F. Scott Fitzgerald',1,'1925-04-10',1);
INSERT INTO NOVEL(TITLE,AUTHOR,GENRE_ID,PUBLISHED_DATE,AVAILABLE)
values('Sapiens: A Brief History of Humankind','Yuval Noah Harari',2,'2011-01-01',1);
INSERT INTO NOVEL(TITLE,AUTHOR,GENRE_ID,PUBLISHED_DATE,AVAILABLE)
values('Harry Potter and the Sorcerer''s Stone','J.K. Rowling',3,'1997-06-26',0);
INSERT INTO NOVEL(TITLE,AUTHOR,GENRE_ID,PUBLISHED_DATE,AVAILABLE)
values('To Kill a Mockingbird','Harper Lee',1,'1960-07-11',1);
INSERT INTO NOVEL(TITLE,AUTHOR,GENRE_ID,PUBLISHED_DATE,AVAILABLE)
values('1984','George Orwell',4,'1949-06-08',0);
INSERT INTO NOVEL(TITLE,AUTHOR,GENRE_ID,PUBLISHED_DATE,AVAILABLE)
values('The Catcher in the Rye','J.D. Salinger',1,'1951-07-16',1);
INSERT INTO NOVEL(TITLE,AUTHOR,GENRE_ID,PUBLISHED_DATE,AVAILABLE)
values('Brave New World','Aldous Huxley',4,'1932-01-01',1);
INSERT INTO NOVEL(TITLE,AUTHOR,GENRE_ID,PUBLISHED_DATE,AVAILABLE)
values('The Hobbit','J.R.R. Tolkien',3,'1937-09-21',0);
INSERT INTO NOVEL(TITLE,AUTHOR,GENRE_ID,PUBLISHED_DATE,AVAILABLE)
values('Meditations','Marcus Aurelius',7,'1800-01-01',1);
INSERT INTO NOVEL(TITLE,AUTHOR,GENRE_ID,PUBLISHED_DATE,AVAILABLE)
values('Prejudice','Jane Austen',5,'1813-01-25',1);


-- 더미 데이터
INSERT INTO NOVEL(TITLE,AUTHOR,GENRE_ID,PUBLISHED_DATE,AVAILABLE)
(SELECT TITLE,AUTHOR,GENRE_ID,PUBLISHED_DATE,AVAILABLE FROM NOVEL);


-- 저자, 장르, 타이틀, 평균평점, 
SELECT n.NOVEL_ID, n.AUTHOR,g.GENRE_NAME,(SELECT avg(g.RATING)FROM GENRE g WHERE g.no  ) n.AVAILABLE 
FROM NOVEL n LEFT JOIN GENRE g ON n.GENRE_ID = g.GENRE_ID
ORDER BY n.NOVEL_ID DESC

SELECT g.NOVEL_ID, avg(g.RATING)
FROM GRADE g 
GROUP by g.NOVEL_ID
	
